[package]
name = "rust_json_parser"
version = "0.1.0"
edition = "2021"
authors = ["Anshul <anshulspartan141@gmail.com>"]

[lib]
name = "mylib"
crate-type = ["cdylib"]


[dependencies]
serde_json = "1.0"

[profile.release]
lto = true
codegen-units = 1
